spring:
  application:
    name: ms-order
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ms
    password: ms5
    url: jdbc:postgresql://localhost:5432/ms-order
  jpa:
      hibernate:
        ddl-auto: none

server:
  port: 8081

client:
  urls:
    menu-service: http://localhost:8081/api/v1/menu-items

