spring:
  application:
    name: ms-order
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ms
    password: ms5
    url: jdbc:postgresql://localhost:5432/ms-order
  jpa:
      hibernate:
        ddl-auto: none

server:
  port: 8082

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

